version: "3.8"

services:
  mysql:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
  afip-api:
    container_name: afip-api
    build:
      context: ./packages/afip-api # ruta a tu microservicio
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    ports:
      - "4001:4001" # puerto expuesto, el mismo que configuraste en main.ts
    environment:
      - APP_ENV=${APP_ENV}
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./packages/afip-api/certs:/app/certs:ro # <--- bind mount de tu carpeta local
    networks:
      - app-network

  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    restart: always
    ports:
      - "3003:3000" # Usamos 3003 externamente, 3000 internamente
    environment:
      - DEFAULT_WAIT_TIMEOUT=30
      - DISABLE_GOOGLE_CHROME=false
    volumes:
      - gotenberg_data:/tmp
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: ./packages/api
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    ports:
      - "3001:3001"
    environment:
      - APP_ENV=${APP_ENV}
      - GOTENBERG_URL=http://gotenberg:3000 # Usa el nombre del servicio y puerto interno
      - TZ=America/Argentina/Buenos_Aires
      - AFIP_HOST=afip-api
      # JWT Configuration
      - AUTH_JWT_SECRET=this-is-a-very-strong-secret-key-for-jwt-tokens
      - AUTH_JWT_EXPIRED=10m
      - AUTH_JWT_REFRESH_SECRET=this-is-a-very-strong-refresh-secret-key
      - AUTH_JWT_REFRESH_EXPIRED=24h
      # Database Configuration
      - MYSQL_DATABASE=pintegralco
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=dev_password_123
      - MYSQL_USER=root
      - MYSQL_HOST=mysql
      # Additional Auth Config
      - AUTH_KEY=dasdsadsadsadsdsa
      - AUTH_APP=nombre_app
      - COOKIE_EXPIRED=86399999
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=false
      - COOKIE_SESSION_TOKEN_NAME=local_pinte_refresh_token
      - AUTH_OPTION_NAME=local_pinte
    volumes:
      - files_data:/app/files
    depends_on:
      mysql:
        condition: service_healthy
      gotenberg:
        condition: service_started
      afip-api:
        condition: service_started

    networks:
      - app-network

  front:
    container_name: front
    build:
      context: ./packages/front
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - api
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - front
      - api
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  certbot_challenges:
  files_data:
  gotenberg_data:
  certs_data:
