export const CATEGORIAS = {
    INGRESOS_PROYECTADOS: 1,
    INGRESOS_PROYECTADOS_OTS: 2,
    EFECTIVO: 3,
    CHEQUES_DIFERIDOS: 4,
    TRANSFERENCIAS: 5,

} as const

export const CATEGORIAS_CODIGOS = {
    DESCUBIERTOS_BANCOS: '1',
    DEVOLUCION_DESCUBIERTOS: '2',
} as const