export const COMISIONES = {
    MANO_DE_OBRA: 180,
    SUMINISTROS: 80,
    MATERIALES: 180,
}

export const PRESUPUESTO_EXCEL_HEADER_MAP: Record<string, string> = {
    id: "N°",
    comprador: "Comprador",
    fecha: "Fecha inicio",
    "vendedor.nombre": "Vendedor",
    "cliente.nombre": "Cliente",
    descripcionCorta: "Descripción corta",
    "procesoGeneral.nombre": "Proceso",
    "area.nombre": "Area",
    fechaFabricacionEstimada: "Fecha fabricación",
    fechaEntregaEstimada: "Fecha entrega",
    progreso: "Progreso",
    costoTotal: "Total c/ estimado",
    ventaTotal: "Venta",
    bab: "Rentabilidad",
    "%": "Rentabilidad %",
    montoCobrado: "Monto Cobrado",
    montoRetenciones: "Monto Retenciones",
    montoFacturado: "Monto Facturado",
    diasProgreso: "Días Progreso",
    fechaEntregado: "Fecha entregado",
    disenoEstatus: "Estatus de diseño",
    costeoEstatus: "Estatus costeo técnico",
    fechaVerificacionAlmacen: "Verificado por almacen",
    fechaVerificacionServicio: "Verificado por Servicio",
    fechaRecepcionAlmacen: "Recibido por almacen",
    costeoComercialEstatus: "Estatus costeo comercial",
    facturacionEstatus: "Estatus facturación",
    cobranzaEstatus: "Estatus cobranza",
    produccionEstatus: "Estatus trabajos",
};
