export const USUARIO_STATUS = {
    ESTADO_BLOQUEADO: 1,
    ESTADO_DESBLOQUEADO: 2,
    ESTADO_ERROR_PASSWORD: 3,
    ESTADO_LOGIN_CORRECTO: 4,
    ESTADO_CAMBIO_CLAVE: 5,
    ESTADO_RESET_PASSWORD: 6,
    ESTADO_USUARIO_ACTIVADO: 7,
};
